### ISSUE TITLE
Publish IPPCore

### ISSUE THREAD

**Issue by JayKickliter** [lindahua/IPPCore.jl#4]
I'd like to publish IPPDSP soon, but it depends on IPPCore. Are you planning on publishing it? If you are, and there is work that needs to be done first, I'd be happy to do it.

**Comment by lindahua** [comment]
I will publish it later today

**Comment by JayKickliter** [comment]
Thanks!

**Comment by JayKickliter** [comment]
I finally got around to publishing IPPDSP, and immediately got an email from Ian saying it fails. It looks like IPPCore wasn't tagged properly, so it isn't up to date. Would mind tagging and republishing? Thanks.

**Comment by lindahua** [comment]
This package has been published, with latest commit tagged as v0.2.1. 

@JayKickliter I also added you to the collaborator list. Please feel free to make changes as you see fit.

**Comment by RoyiAvital** [comment]
Is there a way to expose all Intel IPP functions to Julia?
